df_paid_membership:
  «Paid_Membership»_Enable:
    default: false
    client: true
  «Paid_Membership»_The_maximum_number_of_a_subscription_remaining_days_when_the_«Membership»_top_menu_ item_should_be_shown_again_to_an_already_subscribed_customer?:
    default: 7
    client: true
  «Paid_Membership»_Trial_Period:
    default: 0
    client: true
  «Paid_Membership»_Text_Above:
    default: "A text above the plans.<br/>You can use <b>HTML tags</b>, [u]BBCodes[/u] and *Markdown* here."
    client: true
    type: df_editor
  «Paid_Membership»_Menu_Item_Title:
    default: 'Membership'
    client: true
  «Paid_Membership»_Menu_Item_Tooltip:
    default: 'Paid Membership'
    client: true
  «Paid_Membership»_«Sign_Up»_Button_Label:
    default: 'Sign Up!'
    client: true
  «Paid_Membership»_Success_URL:
    default: 'profile'
    client: true
  «Paid_Membership»_Plans:
    default: ''
    client: true
    type: paid_membership_plans