df_paid_membership:
  «Paid_Membership»_Enable:
    default: false
    client: true
  «Paid_Membership»_Recurring:
    default: true
    client: true
    hidden: true
  «Paid_Membership»_Text_Above:
    default: "A text above the plans.<br/>You can use <b>HTML tags</b>, [u]BBCodes[/u] and *Markdown* here."
    client: true
    type: df_editor
  «Paid_Membership»_Plans:
    default: ''
    client: true
    type: paid_membership_plans